name: Publish to pip

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # You can specify the Python version you need


      - name: Check if version is in pyproject.toml
        run: |
          # Check if the version number is in pyproject.toml
          if grep -q "version\s*=\s*['\"]\?[0-9.-]\+['\"]\?" pyproject.toml; then
            echo "Version is found in pyproject.toml."
          else
            echo "ERROR - Version not found in pyproject.toml."
          fi
        shell: bash


      - name: Extract version number from pyproject.toml
        run: |
          # Use grep to find the line containing the version number
          version_line=$(grep -E "version\s*=" pyproject.toml)

          # Use awk to extract the version number
          version=$(echo "$version_line" | awk -F"['\"]" '{print $2}')

          # Echo the extracted version number
          echo "Version number is: $version"
          echo "version=$version" >> $GITHUB_ENV
        shell: bash


      - name: Increment the rightmost integer in the version
        run: |
          # Increment the rightmost integer by 1
          IFS='.' read -a version_parts <<< "$version"
          last_part="${version_parts[-1]}"
          new_last_part=$((last_part + 1))
          version_parts[-1]=$new_last_part
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"

          # Update the version in pyproject.toml
          sed -i "s/\(version\s*=\s*['\"]\?\)[0-9.-]\+\(['\"]\?\)/\1$new_version\2/" pyproject.toml

          # Echo the updated version
          echo "Updated version is below:"
          echo "new_version=$new_version" >> $GITHUB_ENV
        shell: bash


      - name: Create a new branch
        run: |
          echo "creating branch: "
          branch="feature/update-version-$new_version"
          echo "branch=$branch" >> $GITHUB_ENV
          git checkout -b feature/update-version-$new_version
          git push origin feature/update-version-$new_version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}


      - name: Commit and Push Changes
        run: |
          git config --global user.email "suleyleeuw@gmail.com"
          git config --global user.name "SuleyNL"
          
          # Switch to the update_version branch
          git fetch
          git checkout $branch
          git add pyproject.toml
          
          # Extract the current branch name from the github.event variable
          current_branch=${{ github.ref }} >> $GITHUB_ENV
          echo "current branch is: $current_branch"
          echo "Branch to push to is: $branch"
          
          # Commit the changes in pyproject.toml
          git commit -am "Increment version from $version to $new_version"
      
          # Push the changes to the current branch
          #git push origin $branch --set-upstream origin $branch
          git push origin HEAD:$branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      # The version can also be updated using a version in the github repo, this must first be analyzed for pros and cons
      #- name: Update version in src/version.py and pyproject.toml
      #  run: |
      #    # Increment the version in src/version.py
      #    python -c "import re; f=open('src/version.py', 'r+'); v=re.sub(r'(\d+)', lambda x: str(int(x.group(0))+1), f.read()); f.seek(0); f.write(v); f.truncate(); f.close()"
      #    # Update the version in pyproject.toml
      #    sed -i 's/\(version = "\)[0-9.]*\(".*\)/\1NEW_VERSION\2/' pyproject.toml
      #  env:
      #    NEW_VERSION: ${{ github.run_number }}

      - name: Create Pull Request
        run: |
          pr_title="Update Version"
          pr_body="This is an automated update of version in pyproject.toml. This action is performed by publish.yml."
          gh pr create --base main --head $branch --title "$pr_title" --body "$pr_body"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}


      - name: Request Reviews and Merge
        run: |
          # Use the gh pr review command to request changes
          #gh pr review $branch --request-changes SuleyNL
          gh pr review $branch --request-changes
          
          # Wait for reviews and approvals
          gh pr check $branch --wait
          
          # Merge the pull request
          gh pr merge $branch --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}


      - name: Build package
        run: |
          python -m pip install --upgrade pdm
          pdm build
        working-directory: ./  # Specify the directory where pyproject.toml is located


      - name: Upload package to PyPI
        run: |
          python -m pip install twine
          twine upload dist/extractable-* --verbose
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API }}
