on: [push]



jobs:
  code-coverage:
    runs-on: windows-latest #windows first, later we try other OS's for cross OS compatibility
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2



      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}



      - uses: actions/cache@v3
        with:
          path: |
            ${{ env.pythonLocation }}
            .venv
          key: pytest-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'pdm.lock') }}



      - name: Install dependencies
        # we use --no-lock so it doesn't update the lock file if it's out of date.
        run: |
          python -m pip install --upgrade pdm
          pdm install --no-lock -G test -G pipeline

 

      - name: Run PyTest
        # run pytest on all files that start with "test_" and have a ".py" extension.
        run: |
          pdm run pytest -k "./tests/*/test_*.py"
          
